### ISSUE TITLE
Remove `prefers-reduced-motion` file

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/wp-scaffold#128]
### Is your enhancement related to a problem? Please describe.

I think [this file](https://github.com/10up/wp-scaffold/blob/trunk/themes/10up-theme/assets/css/frontend/base/prefers-reduced-motion.css) should probably be removed from the scaffold:

```css
/*
 * Resources on prefers-reduced-motion:
 * https://webkit.org/blog-files/prefers-reduced-motion/prm.htm
 * https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
 */
@media (prefers-reduced-motion: reduce) {

	*,
	*::before,
	*::after {
		animation-duration: 0.001s !important;
		transition-duration: 0.001s !important;
	}
}
```

I think this is using a very drastic approach and with very high specificity to just nuke animations which doesn't translate well with accessibility. The only concern with animations should be [Vestibular disorders ](http://a11yproject.com/posts/understanding-vestibular-disorders/) related to motion sickness.  However, animations can be great too to combat forms of cognitive disabilities when used to break down complicated concepts or communicate relationships with seemingly unrelated objects. Here's [a good article about researched benefits of animations](http://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity/#section6) in general.

A much slower animation that adds movement could be a valid replacement or even sorting to fade in / fade out without moving.

See https://github.com/10up/Engineering-Best-Practices/pull/385 for a supporting explanation in our Engineering Best Practices.

I'm more than happy to open a PR but I'd rather discuss this as an issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
