### ISSUE TITLE
Add Dark Mode support and guidance

### ISSUE THREAD

**Issue by joesnellpdx** [10up/wp-scaffold#63]
Dark mode is a display options for many. 
Currently, we most often leave it alone and avoid intentionally adding inentional dark mode styles.

Per this [article](https://developer.chrome.com/blog/auto-dark-theme/), Google may be auto enabling an applying a dark mode theme to sites.

There are a few options to explore:

- Intentionally disable dark mode with this: `<meta name="color-scheme" content="only light">`
- Add guidance and starter css for enabling dark mode with intentionally set custom properties
- Actually apply a dark mode theme by default - with guidance on how to customize / modify as needed
- If we add a dark mode option, should we add / provide guidance for toggling on or off by the user?

**Comment by xavortm** [comment]
I think that if we add the dark mode support by default, it would be the obvious decision that the developer has to make - continue supporting it or disable the dark mode support (which will be documented). 

And for dark mode tactics on the CSS properties, I found this to work well:
```css
:root {
  --c-base: white;
  --c-base--invert: black;

  --c-text: black;
  --c-text--invert: white;

  --c-primary: red;
  --c-primary--invert: white;
}

@media (prefers-color-scheme: dark) {
  :root {
    --c-base: black;
    --c-base--invert: white;

    --c-text: white;
    --c-text--invert: black;

    --c-primary: tomato; /* Red becomes too dark to see, so we make it lighter */
    --c-primary--invert: black; /* White won't be readable, so the text becomes black. */
  }
}
```

The idea is that each color has an "invert". This is a color you can place as the opposite (background-foreground) that has contrast. Base would be body, base-invert would be the text on it.

For button, —primary is the red color, —primary—invert would be the text on top of the button.

This allows for change to the primary color without worry for the contrast of the text itself. Here is another example: https://codepen.io/xavortm/pen/RwLrjZW - this showcases the codebase above. 

I think that the —invert suffix helps in dark mode as often, the color itself is slightly adjusted. 

## Color changes:
With dark mode, as mentioned above, the color will also change (primary color, accent color etc). This is an excerpt from Google Material design: https://material.io/design/color/dark-theme.html#anatomy

- Desaturation: Primary colors are desaturated so they pass the Web Content Accessibility Guidelines’ (WCAG) AA standard of at least 4.5:1 (when used with body text) at all elevation levels
- Limited color: Large surfaces use a dark surface color, with limited color accents (light, desaturated and bright, saturated colors)

And because we have to desaturate the colors, it's possible that we need to also change the invert. Brighter red, will no longer work with white text to keep contrast. In fact, sometimes it could be a design decision to add color to the invert as well, so we have Light red background with deep red text
![CleanShot 2021-12-06 at 15 29 45](https://user-images.githubusercontent.com/2004664/144854512-a497ba9d-c252-4194-86ba-7be1d59bbaf1.png)
