### ISSUE TITLE
Add Initial Markup

### ISSUE THREAD

**Issue by dmtrmrv** [10up/wp-scaffold#79]
### Is your enhancement related to a problem? Please describe.

Most of the sites we build require common markup elements like header, main area, footer, and a "skip to main content" link. We can provide this markup in the scaffold. Following structure worked well for me on previous projects and I don't recall a case when I needed something completely different:

``` php
<!DOCTYPE html>
<html <?php language_attributes(); ?> class="no-js">
  <head>
    <meta charset="<?php bloginfo( 'charset' ); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?php wp_head(); ?>
  </head>

  <body <?php body_class(); ?>>
    <?php wp_body_open(); ?>
    <div id="page" class="site">
      <header id="masthead" class="site__header site-header">
        <div class="site-header__inner">
          <a class="site-header__skip-link visually-hidden" href="#primary"><?php esc_html_e( 'Skip to content', 'textdomain' ); ?></a>
          <h1><?php bloginfo( 'name' ); ?></h1>
        </div>
      </header>

      <main id="primary" class="site__main site-main">
        <?php if ( have_posts() ) : ?>
          <?php while ( have_posts() ) : the_post(); ?>
            <h2><?php the_title(); ?></h1>
          <?php endwhile; ?>
        <?php endif; ?>
      </main>

      <footer id="colophon" class="site__footer site-footer">
        <div class="site-footer__inner">
          <!-- Footer content goes here -->
        </div>
      </footer>
  </div>
  <?php wp_footer(); ?>
  </body>
</html>
```

This is a combined markup from `header.php`, `index|page|post.php`, and `footer.php`.

It is design agnostic but gives flexibility in terms of styling the header and footer position they way we want. Here's a quick CSS example of how to make a layout with a sticky header and footer at the bottom (regardless of the amount of content):

```css
html,
body {
	height: 100%;
	width: 100%;
}

body {
	padding-top: var(--h-header);

	&.admin-bar {
		padding-top: calc(var(--h-header) + var(--h-admin-bar));

		@media (--wp-medium) {
			padding-top: calc(var(--h-header) + var(--h-admin-bar-medium));
		}
	}
}

.site {
	display: flex;
	flex-direction: column;
	min-height: 100%;
	width: 100%;
}

.site__header {
	height: var(--h-header);
	left: 0;
	position: fixed;
	top: 0;
	width: 100%;
	z-index: 1;

	@nest .admin-bar & {
		top: var(--h-admin-bar);

		@media (--wp-medium) {
			top: var(--h-admin-bar-medium);
		}
	}
}

.site__main {
	flex-basis: auto;
	flex-grow: 1;
	flex-shrink: 0;
}

.site__footer {
	flex-shrink: 0;
	height: var(--h-header);
	width: 100%;
}
```

Adding default CSS is a bigger discussion though. I'm not suggesting adding this snippet as part of this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
